name: Publish to crates.io
on:
  push:
    tags:
      - "*"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - run: cargo publish -p tunnelto_protocol --token "${{ secrets.CARGO_REGISTRY_TOKEN }}"
      - run: cargo publish -p tunnelto --token "${{ secrets.CARGO_REGISTRY_TOKEN }}"
